### ISSUE TITLE
CFLAGS is not passed on

### ISSUE THREAD

**Issue by svigerske** [coin-or-tools/ThirdParty-Glpk#2]
In branch autotools-update, the CFLAGS I set in my config.site file are not used in the Glpk build.

They are present in the base Makefile, but not in the one of glpk itself:
```
$ grep CFLAGS Makefile 
CFLAGS =  -fvisibility=hidden -g
$ grep CFLAGS glpk/Makefile 
CFLAGS = 
```

@LouHafer, I cannot assign you, probably because you have no permissions here. (And I cannot make you a project member, as this is only coin-or-tools and not coin-or.)

**Comment by svigerske** [comment]
Ah yes, now I remember that you said that one needs to run configure with -C. Then things seem to be passed on indeed.
Is there some way around this? Like enforcing -C? Or just aborting if one forgot to set -C?

**Comment by tkralphs** [comment]
I just invited @LouHafer to be a member of the organization and the BuildTools team. This all seems a bit hackish to me. If we are going to use Glpk's native configure, then it seems strange to over-write all of its choices. What if at some point, Glpk starts to add `-std=c++11` and we don't? Isn't the point of using the native configure to capture this? 

Once we get rid of monolithic builds, then this problem becomes universal, not just with OsiGlpk. The only way to ensure consistent use of flags will be to build with `coinbrew`. Of course, the problem is a bit different between COIN projects, since we at least know that they are all using the same defaults, etc. But isn't just enforcing the use of `coinbrew` enough? Then we have control over the flags and to be passed to configure and can just add `CFLAGS=...` if we want. I guess I haven't poked at this enough to understand the issue and what's really going on, so sorry if this is an uninformed question. I'll try to take a closer look later on.

**Comment by LouHafer** [comment]
(Stefan, you've already read this in email.) The justification for attempting this is that (for now, at least) COIN's build smarts are better than glpk's, particularly for these faux-Windows environments. On the other hand, glpk's native configure knows the details of glpk's code layout and options. Done right, we should get the best of both worlds. We'll know if it's done right if the upgrade to glpk 4.66 is a simple matter of running a few scripts.  There are some fine points. Passing things like CFLAGS to a subconfigure is awkward because configure is on the watch for them (`significant variables that change the environment') and declares an error when it sees the subconfigure called with different options than the top-level configure, particularly with caching enabled. Also, we've used glpk to supply the AMD API. That, too, requires tweaking glpk's native configure to install amd.h and export symbols.

I have some ideas to work around the issues. Give me a few days to experiment.

**Comment by svigerske** [comment]
I removed expecting Glpk's AMD API in Clp with coin-or/Clp@7e1ff4d0556. It seems to be cleaner to me to look for a real SuiteSparse only.

**Comment by LouHafer** [comment]
As per issue #3, I've changed the approach to use COIN initialisation and build smarts macros. @svigerske, I'm hopeful this will fix the problem. There are likely rough edges here but I thought I should get this up and let folks beat on it.

**Comment by svigerske** [comment]
Works good for me.
